apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubevirt-vm-test
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 10.0.0.50
    path: /mnt/volume01/kubevirt